# Generated by Django 5.0.2 on 2024-03-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('specialists', '0004_alter_availability_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consulting_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='specialists.consultingroom'),
        ),
    ]
