# Generated by Django 5.0.2 on 2024-03-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_consulting_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Sin confirmar'), (1, 'Confirmado'), (2, 'Cancelado')], default=0),
        ),
    ]
