# Generated by Django 5.0.2 on 2024-03-08 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultation_status'),
        ('specialists', '0004_alter_availability_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consulting_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.consultingroom'),
        ),
    ]
