# Generated by Django 5.0.2 on 2024-02-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0002_alter_availability_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingroom',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
